$(eval $(call test,parse_context_test,utils,boost))
$(eval $(call test,configuration_test,utils,boost))
$(eval $(call test,environment_test,utils,boost))
$(eval $(call test,info_test,utils,boost))
$(eval $(call test,compact_vector_test,arch,boost))
