#! /usr/bin/python

import sys
import builddeps


if len(sys.argv) == 1:
    graph = builddeps.parse_makefile("Makefile")
elif len(sys.argv) == 2:
    graph = builddeps.parse_makefile("Makefile", sys.argv[1])
else:
    graph = builddeps.parse_makefile(sys.argv[2], sys.argv[1])

print "digraph {"

for key in sorted(graph.edges.keys()):
    for value in graph.edges[key]:
        print "  \"%s\" -> \"%s\";" % (key, value)

print "}"


