$(eval $(call test,tick_counter_test,arch,boost))
$(eval $(call test,bitops_test,arch,boost))
$(eval $(call test,cpuid_test,arch,boost))
$(eval $(call test,simd_test,arch,boost))
$(eval $(call test,cmp_xchg_test,arch utils boost_thread-mt,boost))
$(eval $(call test,simd_vector_test,arch,boost))
$(eval $(call test,backtrace_test,arch,boost))
$(eval $(call test,bit_range_ops_test,arch,boost))
