$(eval $(call test,date_test,types arch utils,boost valgrind))
$(eval $(call test,localdate_test,types arch utils,boost valgrind))
$(eval $(call test,id_test,types,boost valgrind))
$(eval $(call test,string_test,types arch utils boost_regex,boost))
$(eval $(call program,id_profile,types))
