/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "flume_constants.h"



const flumeConstants g_flume_constants;

flumeConstants::flumeConstants() {
}



