// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ThriftFlumeEventServer.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class ThriftFlumeEventServerHandler : virtual public ThriftFlumeEventServerIf {
 public:
  ThriftFlumeEventServerHandler() {
    // Your initialization goes here
  }

  void append(const ThriftFlumeEvent& evt) {
    // Your implementation goes here
    printf("append\n");
  }

  void close() {
    // Your implementation goes here
    printf("close\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ThriftFlumeEventServerHandler> handler(new ThriftFlumeEventServerHandler());
  shared_ptr<TProcessor> processor(new ThriftFlumeEventServerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

